name: benchmark
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  pytest-benchmark:
    name: pytest-benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pymovements repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install tox
        run: python -m pip install tox

      - name: Setup benchmark environment
        run: tox -vv --notest -e benchmark

      - name: Run benchmark
        run: tox --skip-pkg-install -e benchmark

      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: benchmark-${{ github.ref_name }}-${{ github.run_id }}
          restore-keys: benchmark-main

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: pytest-benchmark
          tool: 'pytest'
          output-file-path: benchmark-data.json
          external-data-json-path: ./cache/benchmark-data.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false
          alert-threshold: '150%'
          comment-on-alert: true
          fail-on-alert: true
          summary-always: true
          alert-comment-cc-users: '@dkrako,@SiQube'
