name: build

on:
  push:
    branches: [main]
  workflow_call:

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build:
    name: Build distribution packages

    needs: tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install build dependency
      run: python -m pip install build

    - name: Build a binary wheel and a source tarball
      run: python -m build

    - name: Upload distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: pymovements-distribution-packages
        path: dist/
        if-no-files-found: error
        retention-days: 1
