name: pylint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pylint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install base python for tox
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install tox
        run: python -m pip install tox
      - name: Setup test environment
        run: tox -vv --notest -e pylint
      - name: Run test
        run: tox --skip-pkg-install -e pylint
